#! /usr/bin/env node

var child_process = require('child_process');

var cp = child_process.exec('fehooks lint --color');

var data = '';

cp.stdout.on('data', function (chunk) {
    data += chunk.toString();
});

cp.on('close', function () {
    if (data.indexOf('problems') > -1 && data.indexOf('OKAY') === -1) {
        console.log(data.trim());
        process.exit(1);
    }
    else {
        console.log(data);
        console.log('Commiting...');
    }
});
